/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("games").del();
  await knex("games").insert([
    {
      id: 1,
      user_id: 1,
      opponent: "Jane Smith",
      score: "11-6",
      date: "2024-06-01",
      win: true,
    },
    {
      id: 2,
      user_id: 1,
      opponent: "Alice Johnson",
      score: "8-11",
      date: "2024-06-02",
      win: false,
    },
    {
      id: 3,
      user_id: 2,
      opponent: "Bob Brown",
      score: "11-9",
      date: "2024-06-03",
      win: true,
    },
    {
      id: 4,
      user_id: 2,
      opponent: "Charlie Davis",
      score: "11-5",
      date: "2024-06-04",
      win: true,
    },
    {
      id: 5,
      user_id: 3,
      opponent: "John Doe",
      score: "11-10",
      date: "2024-06-05",
      win: true,
    },
    {
      id: 6,
      user_id: 3,
      opponent: "Jane Smith",
      score: "7-11",
      date: "2024-06-06",
      win: false,
    },
    {
      id: 7,
      user_id: 4,
      opponent: "Alice Johnson",
      score: "11-8",
      date: "2024-06-07",
      win: true,
    },
    {
      id: 8,
      user_id: 4,
      opponent: "Charlie Davis",
      score: "9-11",
      date: "2024-06-08",
      win: false,
    },
    {
      id: 9,
      user_id: 5,
      opponent: "John Doe",
      score: "11-3",
      date: "2024-06-09",
      win: true,
    },
    {
      id: 10,
      user_id: 5,
      opponent: "Bob Brown",
      score: "10-11",
      date: "2024-06-10",
      win: false,
    },
    {
      id: 11,
      user_id: 1,
      opponent: "Charlie Davis",
      score: "11-7",
      date: "2024-06-11",
      win: true,
    },
    {
      id: 12,
      user_id: 2,
      opponent: "Alice Johnson",
      score: "11-4",
      date: "2024-06-12",
      win: true,
    },
    {
      id: 13,
      user_id: 3,
      opponent: "Bob Brown",
      score: "9-11",
      date: "2024-06-13",
      win: false,
    },
    {
      id: 14,
      user_id: 4,
      opponent: "John Doe",
      score: "11-6",
      date: "2024-06-14",
      win: true,
    },
    {
      id: 15,
      user_id: 5,
      opponent: "Jane Smith",
      score: "11-8",
      date: "2024-06-15",
      win: true,
    },
    {
      id: 16,
      user_id: 1,
      opponent: "Bob Brown",
      score: "8-11",
      date: "2024-06-16",
      win: false,
    },
    {
      id: 17,
      user_id: 2,
      opponent: "John Doe",
      score: "11-10",
      date: "2024-06-17",
      win: true,
    },
    {
      id: 18,
      user_id: 3,
      opponent: "Charlie Davis",
      score: "11-9",
      date: "2024-06-18",
      win: true,
    },
    {
      id: 19,
      user_id: 4,
      opponent: "Jane Smith",
      score: "7-11",
      date: "2024-06-19",
      win: false,
    },
    {
      id: 20,
      user_id: 5,
      opponent: "Alice Johnson",
      score: "11-5",
      date: "2024-06-20",
      win: true,
    },
  ]);
}
